version: "3.9"

services:
  identity:
    container_name: Identity
    build: 
        dockerfile: Identity/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3002:80
    depends_on:
        - rmq
  search:  
    container_name: Search  
    build: 
        dockerfile: Search/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3001:80
    depends_on:
        - rmq
  user:  
    container_name: user  
    build: 
        dockerfile: user/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3000:80
    depends_on:
        - rmq
  apigateway:  
    container_name: APIGateway  
    build: 
        dockerfile: APIGateway/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3003:80
    depends_on:
        - rmq

  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

networks:
  TM-Network:
    external: true