version: "3.9"

services:
  rmq:
    user: '999'
    image: rabbitmq:3-management-alpine
    container_name: rmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 5s
      retries: 30
    networks:
        - TM-Network

  apigateway:
    container_name: APIGateway
    build:
        dockerfile: APIGateway/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3000:80
    depends_on:
      rmq:
        condition: service_healthy

  identity:
    container_name: Identity
    build:
        dockerfile: Identity/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3001:80
    depends_on:
      rmq:
        condition: service_healthy

  search:
    container_name: Search
    build:
        dockerfile: Search/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3002:80
    depends_on:
      rmq:
        condition: service_healthy

  user:
    container_name: user
    build:
        dockerfile: user/Dockerfile
        context: .
    networks:
        - TM-Network
    ports:
      - 3003:80
    depends_on:
      rmq:
        condition: service_healthy

networks:
  TM-Network:
    external: true
